### ISSUE TITLE
Doesn't recognise p8scii in btn and btnp

### ISSUE THREAD

**Issue by mika76** [PictElm/pico8code#2]
eg
```lua
if btn(⬅️) then
 move(p1,-1)
end
```

the arrow is unrecognised an an "unexpected symbol"

**Comment by naclsn** [comment]
Oh indeed! Seems the underlying parse does not accept these weird characters specific to PICO-8; I'll have a look into that.

**Comment by naclsn** [comment]
It should now (0.0.5) accept these special variable names.
