### ISSUE TITLE
Doesn't handle #import

### ISSUE THREAD

**Issue by mika76** [PictElm/pico8code#3]
I have an import file in my .p8

```lua
#import debug.lua
```
but it fails with "cannot read file"

**Comment by naclsn** [comment]
I assume you mean `#include`?

I don't have VSCode installed (I can't get it to work) but are you sure the included file exists? Where is it located in relation to the including file?

The PICO-8 seems to always include relatively to the including file.

If the error message is indeed the "could not read file" then it should also show more, in particular the path of the file it is trying to include.

**Comment by mika76** [comment]
Whoops sorry, yeah I did mean `#include debug.lua` 🤣 

![Screenshot 2022-11-29 at 12 53 21](https://user-images.githubusercontent.com/229311/204522195-0ff2705d-81e7-4305-9e4d-391a40fad9be.png)

Yeah you're right the path is showing, but the file exists and is right there. Maybe because it's a .lua file and not a .p8 file?

Also it does not seem to allow it being commented out...
![Screenshot 2022-11-29 at 12 52 31](https://user-images.githubusercontent.com/229311/204522031-e59ce1b2-6fa4-49e2-b8f4-7ad859f382fc.png)

**Comment by naclsn** [comment]
Well then, that's interesting... The extension in the file name is not what determines how the inclusion works, but the header in the included file itself does. That means it just does not find it...

Not sure if it might have to do with the space in the path..?

Also, indeed it does not recognize the comment! Thank you for pointing it out! I will also implement a quick fix for this, but I that's a hack; eg. it will not work for the case below (as in it will still try to read the file):
```lua
--[[
#include some.p8
]]
```

Proper fix for this would come with a larger redesign..

**Comment by naclsn** [comment]
The 'file not found' should be fixed now (0.0.5) -- it had to do with the space in file path), and it will no longer try to process an include that is commented out with a single line `--`.
